LIST_SUBREDDITS = list(dict.fromkeys(s.lower() for s in [
    'memes', 'Seaofthieves', 'Warframe', 'forhonor',
    'DeepRockGalactic', 'Eldenring', 'shittydarksouls',

    'funny', 'AskReddit', 'gaming', 'aww', 'Music', 'pics', 'science',
    'worldnews', 'videos', 'todayilearned', 'movies', 'news', 'gifs',
    'IAmA', 'askscience', 'EarthPorn', 'books', 'television', 'tifu',
    'LifeProTips', 'nottheonion', 'DIY', 'space', 'sports', 'history',
    'Showerthoughts', 'Documentaries', 'philosophy', 'Futurology',
    'personalfinance', 'nosleep', 'Jokes', 'food', 'OldSchoolCool',
    'dataisbeautiful', 'UpliftingNews', 'photoshopbattles',
    'explainlikeimfive', 'creepy', 'GetMotivated', 'WritingPrompts',
    'gadgets', 'listentothis', 'Art', 'InternetIsBeautiful',
    'mildlyinteresting', 'announcements', 'technology', 'me_irl',
    'relationship_advice', 'Anime', 'memeeconomy', 'interestingasfuck',
    'blackmagicfuckery', 'wholesomememes', 'rarepuppers', 'startups',
    'travel', 'programming', 'pcmasterrace', 'Feminism', 'psychology',
    'cringe', 'fitness', 'gamingcirclejerk', 'techsupportgore',
    'instant_regret', 'Unexpected', 'ThereWasAnAttempt',
    'woahdude', 'AnimalsBeingBros', 'cats', 'dogs', 'kidsarefuckingstupid',
    'HumansBeingBros', 'NatureIsFuckingLit', 'madlads', 'facepalm',
    'trashy', 'nextfuckinglevel', 'insanepeoplefacebook', 'Tinder',
    'niceguys', 'ChoosingBeggars', 'interestingasfuck', 'BeAmazed',
    'whatcouldgowrong', 'perfecttiming', 'WinStupidPrizes', 'PrequelMemes',
    'dankmemes', 'historymemes', '2meirl4meirl', 'AdviceAnimals',
    'Animemes', 'Overwatch', 'LeagueOfLegends', 'VALORANT',
    'Minecraft', 'halo', 'DestinyTheGame', 'starcitizen'
]))
